### ISSUE TITLE
Reminder: make a release

### ISSUE THREAD

**Issue by cprogrammer1994** [cprogrammer1994/ModernGL#246] opened 2018-08-28 07:53 UTC
- [ ] check for non merged fixes
- [ ] check for todos

**Comment by cprogrammer1994** [comment] 2018-08-28 07:54
#220 #226 #227

**Comment by einarf** [comment] 2018-08-28 07:57
I think sampler binding might be something for 6.0 if we're considering any changes. Gives a bit more time to think it through properly as well.

**Comment by cprogrammer1994** [comment] 2018-08-28 07:59
I have it marked with a wrong milestone then.

**Comment by einarf** [comment] 2018-08-28 17:35
#227 and #224 would be logical to do in the same release (in my head at least) 😃

**Comment by einarf** [comment] 2018-12-29 00:08
Any chance of a a 5.4.3 release? I just noticed the scope and depth texture bug was still present. It also means the release list here on github will be in sync again as the latest release listed is the broken 5.4.1 version 😄

**Comment by cprogrammer1994** [comment] 2018-12-30 09:14
Hi, thank you pointing it out :)
Do you have a PyPI account? I would need help building the mac wheels. I would like to add you as a maintainer.

Are you using the master? Do we have non merged fixes?

**Comment by einarf** [comment] 2018-12-30 11:16
I can definitely help building releases. My username on pypi is `einarf`.
I'm using latest master in dev always.
I'd say just merge the most straight forward pull requests currently lingering.

**Comment by einarf** [comment] 2018-12-30 13:32
EDIT: I got it building on OS X 10.14 now as well. 

The issue is pretty well described here : https://github.com/pandas-dev/pandas/issues/23424

> The compiler standard library defaults to either libstdc++ or libc++, depending on the targetted macOS version - libstdc++ for 10.8 and below, and libc++ for 10.9 and above. This is determined by the environment variable MACOSX_DEPLOYMENT_TARGET or the compiler option-mmacosx-version-min, defaulting to the system version otherwise.

I should make a PR on that before we release.

**Comment by einarf** [comment] 2018-12-31 17:21
I see I'm now maintainer on pypi, so all is set 👍

**Closed** 2019-01-12 20:30 UTC
